name: Build DoubtCure APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            zlib1g-dev \
            libncurses5-dev \
            libgdbm-dev \
            libnss3-dev \
            libreadline-dev \
            libbz2-dev

      - name: Install buildozer
        run: |
          pip install --upgrade pip
          pip install cython
          pip install buildozer

      - name: Create buildozer.spec file
        run: |
          cat << EOF > buildozer.spec
          [app]
          title = DoubtCure
          package.name = doubtcure
          package.domain = org.doubtcure
          source.include_exts = py,kv,png,jpg,atlas
          source.main = Doubtly.py

          requirements = python3, kivy==2.3.1, kivymd==1.1.1, pillow, plyer, pytesseract, requests, sqlite3
          android.permissions = INTERNET, CAMERA, RECORD_AUDIO, READ_EXTERNAL_STORAGE, WRITE_EXTERNAL_STORAGE

          [buildozer]
          log_level = 2
          warn_on_root = 1
          EOF

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: DoubtCure-APK
          path: bin/*.apk
