name: Build Kivy App (APK)

on:
  push:
    branches:
      - main  # or 'master', the branch you push to
  pull_request:
    branches:
      - main # or 'master'
  workflow_dispatch: # Allows manual trigger from the GitHub Actions tab

jobs:
  build_android:
    # Use Ubuntu for the Buildozer build process
    runs-on: ubuntu-latest
    
    # Set environment variables for Buildozer
    env:
      PACKAGE_NAME: com.doubtcure.app
      APP_TITLE: Doubtcure
      PYTHON_VERSION: 3.9
      
    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: 3. Install prerequisites
        # Buildozer and its dependencies
        run: pip install buildozer cython

      - name: 4. Create and Configure buildozer.spec (API 33, NDK 25b)
        # This step uses 'sed' to ensure the buildozer.spec file has the correct settings
        run: |
          # Initialize buildozer.spec
          buildozer init || true
          
          # Update key settings
          sed -i 's/^title = .*/title = '${{ env.APP_TITLE }}'/' buildozer.spec
          sed -i 's/^package\.name = .*/package.name = '${{ env.PACKAGE_NAME }}'/' buildozer.spec
          sed -i 's/^package\.domain = .*/package.domain = yourcompany.com/' buildozer.spec
          
          # Requirements
          sed -i 's/^requirements = .*/requirements = python3,kivy,kivymd,plyer,requests,Pillow,pytesseract,sqlite3/' buildozer.spec
          
          # Set API levels and NDK
          sed -i 's/^android\.minapi = .*/android.minapi = 24/' buildozer.spec
          sed -i 's/^android\.api = .*/android.api = 33/' buildozer.spec
          sed -i 's/#android\.ndk = .*/android.ndk = 25b/' buildozer.spec # Explicit NDK
          
          # Permissions
          sed -i 's/#android\.permissions =/android.permissions = INTERNET,CAMERA,WRITE_EXTERNAL_STORAGE,RECORD_AUDIO/' buildozer.spec
          
          # Rename app's main file to doubtly.py
          sed -i 's/^source\.include_exts = .*/source.include_exts = py,png,jpg,kv,atlas,xml,json,db/' buildozer.spec
          sed -i 's/^main\.py = .*/main.py = doubtly.py/' buildozer.spec
          
      - name: 5. Clean Buildozer Cache (New Step to force SDK/NDK installation) 👈
        # This deletes the existing Buildozer environment and forces a fresh download
        # of the required Android SDK components (including build-tools/Aidl) in the next step.
        run: buildozer android clean
        
      - name: 6. Build Debug APK
        # This is the command that builds the Android package
        run: buildozer android debug

      - name: 7. Upload APK as Artifact
        # Saves the APK file to the GitHub Actions run page
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_TITLE }}_apk
          path: bin/*.apk

      - name: 8. Get APK name for Release
        id: get_apk_name
        run: echo "APK_FILE=$(basename $(ls bin/*.apk))" >> $GITHUB_OUTPUT
        
      - name: 9. Create GitHub Release with APK
        # Creates a draft release on GitHub for easy download
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{ github.sha }}
          name: Release ${{ github.ref_name }} Build
          files: bin/${{ steps.get_apk_name.outputs.APK_FILE }}
          draft: true
          
