name: Build DoubtCure APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Upgrade pip & Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython

      - name: Create buildozer.spec file
        run: |
          cat << EOF > buildozer.spec
          [app]
          title = DoubtCure
          package.name = doubtcure
          package.domain = org.doubtcure
          source.include_exts = py,kv,png,jpg,atlas

          requirements = python3, kivy==2.3.1, kivymd==1.1.1, pillow, plyer, pytesseract, requests, sqlite3
          android.permissions = INTERNET, CAMERA, RECORD_AUDIO, READ_EXTERNAL_STORAGE, WRITE_EXTERNAL_STORAGE

          [buildozer]
          log_level = 2
          warn_on_root = 1
          EOF

      - name: Build APK with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: DoubtCure-APK
          path: bin/*.apk
